---
inventory:
  plugin: SimpleInventory
  options:
    host_file: "inventory/hosts.yaml"
  transform_function: "load_credentials"
runner:
  plugin: threaded
  options:
    num_workers: 10 # Adjust to increase the amount of parallel processes
logging:
  to_console: True